# Generated by Django 4.1.2 on 2022-12-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_imagemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageMessage',
        ),
    ]
